import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
    {
        user:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'User',
            required:true,
        },
        items:[
            {
                product:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"Product",
                    required:true,
                },
                quantity:{
                    type:Number,
                    required:true,
                }
            }
        ],
        shippingAddress:{
            fullName:{
                type:String,
                required:true,
            },
            address:{
                type:String,
                required:true,
            },
            city:{
                type:String,
                default:"Indore",
            },
            country:{
                type:String,
                default:"India",
            },
            mobileNumber:{
                type:Number,
                required:true,
                match:[/^[6-9]\d{9}$/]
            },
            postalCode:{
                type:String,
                required:true,
            },
        },
        paymentMethod:{
            type:String,
            default:"Cash on Delivery",
        },
        isPaid:{
            type:Boolean,
            default:false,
        },
        paidAt:Date,
        isDelivered:{
            type:Boolean,
            default:false,
        },
        deliveredAt:Date,
        deliveryOTP:{
            code:String,
            expiredAt:Date,
            verified:{
                type:Boolean,
                default:false,
            },
        },
        isOrderCanceled:{
            isTrue:{
                type:Boolean,
                default:false,
            },
            why:{
                type:String,
                default:"",
            }
        },
        totalPrice:{
            type:Number,
            required:true,
        },
    },
    {timestamps:true}
);

const Order = mongoose.model('Order',orderSchema);
export default Order;